### ISSUE TITLE
Unavailable video causing issues in code

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/HGTV.bundle#15]
There is one unavailable video in one of the show Flea Market Flip and it is causing the results to fail, but not sure how to add a Media Not available when using a CreateObject function within the __init__.py

**Comment by Gerk** [comment]
If you check in the google doc we've been working on it should show all of the different errors that can be raised if that's what you're asking.

**Comment by shopgirl284** [comment]
No I know how to word a raise Media Not Available, but cannot seem to figure out how and where to include one within the Create Object function without getting an error in my code that will stop all other videos for that show from returning.
