### ISSUE TITLE
full eipsodes list needs fixed again

### ISSUE THREAD

**Issue by eetjtl** [plexinc-plugins/HGTV.bundle#20]
Can still go to shows and pull up full episodes but it was nice to have the list and not have to look through each show folder.
Also need to look at code as some shows on the web don't have video folders anymore but still have available videos.

**Comment by grigarr** [comment]
It looks like this may need to be rewritten for watch.hgtv.com? http://watch.hgtv.com/ seems to have the full list now.

**Comment by eetjtl** [comment]
looks like a fix pull request is out there now
